=== jmangam/LMSGI_UD4/labXML/clientes/clientes.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sede" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="empleado" type="xs:string" />
                            <xs:element name="fecha_alta" type="xs:string" />
                            <xs:element name="descripcion" type="xs:string" />
                            <xs:element name="cliente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="numero_viviendas" type="xs:string" />
                                        <xs:element name="coste" type="xs:string" />
                                        <xs:element name="resumen" type="xs:string" />
                                        <xs:element name="plazo_alta" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jmangam/LMSGI_UD4/labXML/clientes/clientes_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clientes.xsd">
    <sede cod_sede="1">
         <direccion></direccion>
         <empleado>Rodriguez</empleado>
         <fecha_alta>Martin</fecha_alta>
         <descripcion>Manuel</descripcion>
         <cliente cod_cliente="1">
             <numero_viviendas></numero_viviendas>
             <coste></coste>
             <resumen></resumen>
             <plazo_alta></plazo_alta>
         </cliente>
     </sede>
 </clientes>
